name: date_range
description: A simple way to find a daterange in which a datetime is. Used for db queries.
version: 1.0.3
author: Subbotin Aleksei <darkandjeweled@gmail.com>
homepage: https://github.com/Moonspeaker/date_range

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.9.3